#!/bin/bash
#
# reconfigure vulkan on first startup

set -e

if dpkg -s libhybris-vulkan; then
	dpkg-reconfigure libhybris-vulkan
fi

# we want this to run every boot
runonce-queue configure-vulkan

exit 1
