#!/bin/bash

mkdir -p "/run/systemd/user/gnome-session.target.wants"
ln -s "/usr/lib/systemd/user/furios-keyring-bootstrap.service" "/run/systemd/user/gnome-session.target.wants/furios-keyring-bootstrap.service"

systemctl daemon-reload
